export const STORES_FETCH = 'STORES_FETCH';
export const STORES_POPULATE = 'STORES_POPULATE';
export const STORES_SET_ERROR = 'STORES_SET_ERROR';
export const COWORKERS_FETCH = 'COWORKERS_FETCH';
export const COWORKERS_POPULATE = 'COWORKERS_POPULATE';
export const COWORKERS_SET_ERROR = 'COWORKERS_SET_ERROR';
export const COWORKERS_SEARCH = 'COWORKERS_SEARCH';

export const USER_FETCH = 'USER_FETCH';
export const USER_SET = 'USER_SET';
export const USER_SET_ERROR = 'USER_SET_ERROR';
export const ACTIVE_STORE_SET = 'ACTIVE_STORE_SET';
export const ACTIVE_STORE_SWITCH = 'ACTIVE_STORE_SWITCH';